### ISSUE TITLE
Rewrite the main loop

### ISSUE THREAD

**Issue by dasJ** [inishchith/autoenv#129]
The current main loop has a few downsides. It should really be improved.

Dowsides:
- [ ] Removal of double slashes is a bit hacky (#125)
- [ ] Filesystem crossing is not possible (#118)
- [ ] Parent .env files get executed when navigating at the bottom of the tree
- [ ] Autoenv unload is not possible (#30)
- [ ] Leaving the loop from a .env file is impossible
## Proposal

When the user cd's, we look for the common part of the source- and destination-directory (e.g. coming from `/home/alice/myproject/obj` and going to `/home/alice/myproject/src` has `/home/alice/myproject` in common).

Up from the source directory to the common part, we execute all unload files execpt when crossing a mountpoint. Unless mountpoint crossing is enabled, we will stop executing unload files.

From the common part down to the destination directory, we will execute all .env files.

When `source == destination`, we execute all unload files until we reach the mountpoint and then go back down to the directory, executing all .env files. This is used when initializing autoenv and can be used by the user to force execution.

Each .env file (or unload file) can set a variable like `AUTOENV_STOP` which will stop execution of this direction. So when it's called in an unload script, the .env files are still executed.
